### ISSUE TITLE
nneo_file problem

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/nneo#10]
see email from josh

**Comment by sckott** [comment]
changes in 649ac2bfe9b3c177548fbfa4047396ff24fa838a

**Comment by sckott** [comment]
@jaroberti can you reinstall `devtools::install_github("ropenscilabs/nneo")` and try again with `nneo_wrangle` 

It's now using those long amazon s3 urls to download files. However, I think I may still need to fix some of the other internals you had in the wrangle fxn. Some of the fxn is simplified now since we can go directly from the URLs from `nneo_data` output to fetching the data (so avoiding `nneo_file`)

**Comment by jaroberti** [comment]
@sckott Sure, I'll set some time aside to do this next week.

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
check that the data output is what you expect, and let me know of send PR for stuff that needs fixing

**Comment by jaroberti** [comment]
@sckott reinstalled the new version of nneo and re-ran some examples in neon_wrangle.  Mostly everything is working, however I'm noticing that for profile measurements, e.g., PAR, 2D wind, single aspirated air temperature, the vertical instances of the measurements are not being returned.  It's only returning one vertical level, so I'm assuming if I need to go in and fix some of the logic in the neon_wrangle code or maybe this is occurring upstream somewhere else in one of the other functions I'm calling?  I wanted to check in with you first before I started messing around with stuff.

**Comment by sckott** [comment]
I can't think off the top what that would be due to. 

here's a comparison of the last change you had done to the fxn and then the most recent here on master https://github.com/ropenscilabs/nneo/compare/cc5e4f70cc8e502c1706eca9d83167437da160aa...649ac2bfe9b3c177548fbfa4047396ff24fa838a?w=1 to easily see comparison of changes.

**Comment by jaroberti** [comment]
@sckott I'm heading out on vacation this Wednesday and I'm not sure if I'll have time to investigate before then.  I'll be sure to hop back on this when I get back at the end of next week.  Hopefully it's a small change in the code

**Comment by sckott** [comment]
okay, thanks
