### ISSUE TITLE
NEON API changes

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/nneo#12]
see email thread, and 

- [ ] There are about six remaining data products to transition to the new, long data file URL’s.  With six servers cranking on them, we expect them to be done before the end of the year, and hope for much sooner.
    - The long data file URL’s do indeed expire in an hour, as seen in the “X-Amz-Expires=3599” field.
    - These long data file URL’s shouldn’t change in the foreseeable future.
- [x] The /products and /products/<product id> endpoint
    - has an added changeLogs field that snuck out without documentation.  Documentation coming soon.
    - optionally has an externalData field for products hosted outside of NEON.  Also documentation coming soon.
- [ ] Before the end of the year, we expect to add
    - /taxon (taxa expected in a location) and /samples (collected samples metadata) endpoints.
    - a TBD endpoint to show spatial linking information for our aerial platform

**Comment by sckott** [comment]
changes in 649ac2bfe9b3c177548fbfa4047396ff24fa838a

**Comment by naupaka** [comment]
Glad to see you're still working on this @sckott! I'm hoping to use it to teach using NEON data in Ecology class this semester.

**Comment by sckott** [comment]
awesome - some fixes in the works - hopefully new ver to CRAN soonish
