### ISSUE TITLE
nneo_wrangle problem

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/nneo#8]
@jaroberti this example in the `nneo_wrangle` docs is broken 

```r
nneo_wrangle(site_code="STER",time_start="2017-03-04",data_var="dust",
   time_agr=60)
#> Error in FUN(X[[i]], ...) : subscript out of bounds
```

```r
traceback()
#> 3: lapply(data_all, "[[", i) at nneo_wrangle.R#126
#> 2: do.call("rbind", lapply(data_all, "[[", i)) at nneo_wrangle.R#126
#> 1: nneo_wrangle(site_code = "STER", time_start = "2017-03-04", data_var = "dust", 
#>        time_agr = 60)
```

I can try a fix if you want me to, but if you want to - go ahead

**Comment by jaroberti** [comment]
Hi @sckott. Thanks for letting me know.  We are in the process of regenerating some of our data products from the beginning of this year, which might be the cause of this.  I'll try to fix.  I think replacing "dust" with another NEON data product should suffice, but I'll have to do some testing.  

I'm heading out of the country for a week starting next Wednesday.  Hopefully I can get to this before that.  Should I submit another Pull request when it's fixed?

**Comment by sckott** [comment]
NO problem. A PR sounds good
